---
- hosts: localhost
  connection: local
  tasks:
  - name: caretion of ec2
    ec2: 
      aws_access_key:*********
      aws_secret_key: *********
      key_name: ansible_new
      instance_type: t2.micro
      image: ami-d783a9b8
      region: ap-south-1
      count: 1
      instance_tags:
         name: httpd
      wait: yes
